# Generated by Django 3.1.4 on 2021-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('sprice', models.IntegerField()),
                ('cprice', models.IntegerField()),
                ('img', models.ImageField(blank=True, default='default.png', upload_to='items')),
            ],
        ),
    ]
