# Generated by Django 3.1.4 on 2021-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
